ER図の追加
878is878/Todo_sealion pull request #3
Opened 2024-06-17 04:11 UTC by 878is878

ER図を追加しました。確認お願いします

2024-06-17 04:15 UTC, Tsuchiya2 commented
他の講師が見た際にER図の変遷が確認できるようにしたいので、都度最新のER図をコメント欄に掲載をお願いしたいです。（Gyazo・マークダウン）
よろしくお願いいたします。

2024-06-17 04:22 UTC, 878is878 commented
下記のように、ER図を更新する度ここのコメント欄にリンクを貼る、ということでよろしいでしょうか？

### ER図
![WithToDoER図](https://i.gyazo.com/d4e65423d4ed57b1b942061a6b8e1ed1.png)
gyazo → https://gyazo.com/d4e65423d4ed57b1b942061a6b8e1ed1

2024-06-17 10:14 UTC, shota-hope commented
提出ありがとうございます。
> 下記のように、ER図を更新する度ここのコメント欄にリンクを貼る、ということでよろしいでしょうか？

はい、あっています。

- テーブル名がスネークケースかキャメルケースかで統一すると良いと思いました。
- それぞれのカラム名について、どのように使う予定が簡単に箇条書きでコメントいただけますでしょうか。
- Foodsテーブルとtodotalksテーブルのtypeについて、typeは予約後となっているので違う命名が良いと思います
  - https://railsguides.jp/active_record_basics.html#%E3%82%B9%E3%82%AD%E3%83%BC%E3%83%9E%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%AB

ご確認よろしくお願いします。

2024-06-18 15:18 UTC, 878is878 commented
修正しました。確認よろしくお願いします
![WithToDo2](https://i.gyazo.com/76c35a3cc9f0de3e4d0c5af2a4a2ec12.png)
gyazo : https://gyazo.com/76c35a3cc9f0de3e4d0c5af2a4a2ec12

2024-06-20 02:48 UTC, tmtkzk0823 commented
修正ありがとうございます。
以下、追加のコメントになります。

### Foodsテーブル
food_typeというカラムを持っていますが、typeという命名は`STI`という技術を使用する際によく使われる命名なので、STIを使用しない場合、違う命名に変更することを検討してください。

### TaskScheduled
- start_scd
  -  カラム名をのみを見た時、どんな値が入るカラムかがイメージできないため、命名は省略しないことをおすすめします。また、テーブル名から「タスクのスケジュール」を管理するテーブルという意味は受け取れるので、時間を管理するカラムであれば`start_at`などの命名を検討して下さい。

2024-06-20 06:09 UTC, 878is878 commented
指摘箇所を修正しました。確認お願いします
![WithToDo3](https://i.gyazo.com/279cd6a0793ce48fd4f076f117943987.png)
Gyazo : https://gyazo.com/279cd6a0793ce48fd4f076f117943987

2024-06-20 10:35 UTC, tarakish requested changes
修正確認しました。
以下コメントです！

---

- users
  - 認証はgemを使う予定はないでしょうか？もし何かしらを利用予定であれば必要なカラムのご確認をお願いします。

- profiles
  - 以下のカラムの説明をいただきたいです。enumであればどういう値が入るかも一緒にお願いします。
    - raises
    - departed

- TaskScheduled
  - start_actはstart_actuallyの略かと思いますが少しわかりにくい & start_atとスペルが近いためタイポに気づきにくいと思うので、actual_start_at等明確にしても良さそうです（endも同様）

- Todos
  - 旅に出す時に持たせる育成アイテムはどのカラムになりますか？

- Tasks - Categories - Foods - FoodLogs あたりの関連性のイメージがいまいち掴めなかったので、実際にどういうレコードができてどういう値が入るかご説明いただけますか？

2024-06-20 13:02 UTC, 878is878 commented
>認証はgemを使う予定はないでしょうか？

認証に使用するGemはSorceryを予定しています。それに伴いカラムを修正しました。
 
>以下のカラムの説明をいただきたいです。enumであればどういう値が入るかも一緒にお願いしま>す。
raises
departed

 raises :  育成したトドの数(現在育成中も含む)
 departed :旅立たせたトドの数
	この予定でしたが、一度に飼育できるトドの数が1匹固定なので、departedカラムだけ残すよう変更します。
>start_actはstart_actuallyの略かと思いますが少しわかりにくい & start_atとスペルが近いためタイポに気づきにくいと思うので、actual_start_at等明確にしても良さそうです（endも同様）

TaskScheduledのカラム名を修正しました。

>旅に出す時に持たせる育成アイテムはどのカラムになりますか？

 他のトドと関わる機能は、特定画面に遷移時depart（旅立ち）フラグが真のトドの中からランダムに選出された個体を表示することで実装する予定です。その際、アイテムとなるのはトドの持つタスクに紐づいたご飯(food)とする予定なのでカラムは不要だと判断しました。

>Tasks - Categories - Foods - FoodLogs あたりの関連性のイメージがいまいち掴めなかったので、実際にどういうレコードができてどういう値が入るかご説明いただけますか？

Tasks - Categories - Foods - FoodLogs間の関係は、1つのタスクはある1つのカテゴリに属し、そのカテゴリ（一つのカテゴリにつき１種類のご飯）によってトドのご飯が決定、トドの食事は全て記録される、といった関係になっています。食事の記録は本リリース時に実装予定の統計機能に関わるためテーブルをあらかじめ作成している次第です。

_**例**
ランニング30分というタスクを運動カテゴリで設定
↓
運動カテゴリのタスクはエビ(仮)がご飯として設定されている
↓
ランニング30分のタスクを達成することでエビがトドに与えられる
↓
トドがエビを食べたことがデータベースに記録される_

![WithToDo4](https://i.gyazo.com/58676ffbbab2aa838dbedf06eaf20441.png)
gyazo : https://gyazo.com/58676ffbbab2aa838dbedf06eaf20441

2024-06-21 01:35 UTC, kashiwagi-rena commented
お疲れ様です。

> 他のトドと関わる機能は、特定画面に遷移時depart（旅立ち）フラグが真のトドの中からランダムに選出された個体を表示することで実装する予定です。その際、アイテムとなるのはトドの持つタスクに紐づいたご飯(food)とする予定なのでカラムは不要だと判断しました。

トドは、一匹しか飼育できないことが記載にありますが、タスクはたくさん保持することができると思います。こちらの関係は、トド：タスク ＝1対多の関係と認識しております。上記の説明ですと、「トドを介したユーザー交流機能」で持っていくご飯(food)はランダムにUserの意思とは関係なく持っていかれる認識でよろしいでしょうか？

 > Tasks - Categories - Foods - FoodLogs間の関係は、1つのタスクはある1つのカテゴリに属し、そのカテゴリ（一つのカテゴリにつき１種類のご飯）によってトドのご飯が決定、トドの食事は全て記録される、といった関係になっています。

上記はとてもいい設定だと認識します。利用の際に気になることと思いますので、READMEに記載しておいていただく嬉しいです。（ER図とは関係ないので、検討していただければ幸いです。）

2024-06-21 09:54 UTC, 878is878 commented
>「トドを介したユーザー交流機能」で持っていくご飯(food)はランダムにUserの意思とは関係なく持っていかれる認識でよろしいでしょうか？

タスクリストの内、openがtrueになっており(=公開を許可している)尚且つ達成済みのタスク全てがご飯(food)として変換され、別ユーザーの元へ持っていかれることを想定しています。

>トド：タスク ＝1対多の関係と認識しております

トドとタスクはタスクリストを介して1対多の関係になる認識でいました。トド：タスクの間にも線を引いた方がよろしいでしょうか？

>READMEに記載

ER図LGTM後に追記しますね。

![WithToDo4](https://i.gyazo.com/58676ffbbab2aa838dbedf06eaf20441.png)
gyazo : https://gyazo.com/58676ffbbab2aa838dbedf06eaf20441

2024-06-21 12:21 UTC, ky0613 commented
提出ありがとうございます。
以下コメントになります。

----

- `TaskScheduled`テーブルの`actual_start`カラムが重複しているようです。これは意図的なものでしょうか。
- `Tasks`テーブルと`Categories`テーブルのリレーションが1対1になっている点について説明お願いします。

> トドとタスクはタスクリストを介して1対多の関係になる認識でいました。トド：タスクの間にも線を引いた方がよろしいでしょうか？

ここの線は1対多の関係であれば、特に必要ないと思います！

2024-06-22 01:31 UTC, 878is878 commented
> `TaskScheduled`テーブルの`actual_start`カラムが重複しているようです。これは意図的なものでしょうか。

`actual_end`に修正しました

![WithToDo5](https://i.gyazo.com/7ee159d34b2849debb6e2b4392f9a3d7.png)
Gyazo : https://gyazo.com/7ee159d34b2849debb6e2b4392f9a3d7

2024-06-23 05:18 UTC, tarakish commented
修正確認しました。LGTMです！
次の課題に進んでください。

2024-06-23 09:38 UTC, closed without merging